# Generated by Django 4.2.5 on 2023-09-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photograher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='PhotographerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('gender', models.IntegerField(choices=[(0, 'FEMALE'), (1, 'MALE'), (2, 'OTHER')])),
                ('photographer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='home.photograher')),
            ],
        ),
        migrations.DeleteModel(
            name='DemoTable',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
